//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_log
    {
        public int errorId { get; set; }
        public Nullable<System.DateTime> errorDate { get; set; }
        public Nullable<long> errorNumber { get; set; }
        public Nullable<int> errorSeverity { get; set; }
        public Nullable<int> errorState { get; set; }
        public string errorProcedure { get; set; }
        public Nullable<int> errorLine { get; set; }
        public string errorMessage { get; set; }
        public string errorTable { get; set; }
        public string errorComment { get; set; }
        public Nullable<int> timesProcessed { get; set; }
        public string referrer { get; set; }
    }
}
